name: HLS Repack & Deploy to docs

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch: {}

jobs:
  repack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # persist write credentials

      - name: Build Docker image
        run: |
          docker build -t hls-repack .

      - name: Run Docker container
        # Mount workspace so docs/ is written to host
        run: |
          docker run --rm -v "${{ github.workspace }}":/work hls-repack

      - name: Commit & push docs/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs
          git commit -m "Auto-update HLS output $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit"
          git push
